version: '3'
services:
  proxy:
    container_name: proxy_squid_5.6
    build: .
    ports:
      - 3128:3128
    environment:
      - TZ=UTC
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      # - ./log:/var/log/squid